<a href="https://colab.research.google.com/github/mitshiabopm-bot/Bright-coffee-shop/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as nd

In [3]:
df=pd.read_excel("/content/Bright Coffee Shop Analysis.csv.xlsx")

In [4]:
display(df)

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail
0,1,2023-01-01,07:06:11,2,5,Lower Manhattan,32,3.00,Coffee,Gourmet brewed coffee,Ethiopia Rg
1,2,2023-01-01,07:08:56,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
2,3,2023-01-01,07:14:04,2,5,Lower Manhattan,59,4.50,Drinking Chocolate,Hot chocolate,Dark chocolate Lg
3,4,2023-01-01,07:20:24,1,5,Lower Manhattan,22,2.00,Coffee,Drip coffee,Our Old Time Diner Blend Sm
4,5,2023-01-01,07:22:41,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg
...,...,...,...,...,...,...,...,...,...,...,...
149111,149452,2023-06-30,20:18:41,2,8,Hell's Kitchen,44,2.50,Tea,Brewed herbal tea,Peppermint Rg
149112,149453,2023-06-30,20:25:10,2,8,Hell's Kitchen,49,3.00,Tea,Brewed Black tea,English Breakfast Lg
149113,149454,2023-06-30,20:31:34,1,8,Hell's Kitchen,45,3.00,Tea,Brewed herbal tea,Peppermint Lg
149114,149455,2023-06-30,20:57:19,1,8,Hell's Kitchen,40,3.75,Coffee,Barista Espresso,Cappuccino
149115,149456,2023-06-30,20:57:19,2,8,Hell's Kitchen,64,0.80,Flavours,Regular syrup,Hazelnut syrup

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149116 entries, 0 to 149115
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   transaction_id    149116 non-null  int64
 1   transaction_date  149116 non-null  datetime64[ns]
 2   transaction_time  149116 non-null  object
 3   transaction_qty   149116 non-null  int64
 4   store_id          149116 non-null  int64
 5   store_location    149116 non-null  object
 6   product_id        149116 non-null  int64
 7   unit_price        149116 non-null  float64
 8   product_category  149116 non-null  object
 9   product_type      149116 non-null  object
 10  product_detail    149116 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(4), object(5)
memory usage: 12.5+ MB

##adding the column total amount

In [9]:
df['total_amount']=df['transaction_qty']*df['unit_price']
df

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail,total_amount
0,1,2023-01-01,07:06:11,2,5,Lower Manhattan,32,3.00,Coffee,Gourmet brewed coffee,Ethiopia Rg,6.00
1,2,2023-01-01,07:08:56,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.20
2,3,2023-01-01,07:14:04,2,5,Lower Manhattan,59,4.50,Drinking Chocolate,Hot chocolate,Dark chocolate Lg,9.00
3,4,2023-01-01,07:20:24,1,5,Lower Manhattan,22,2.00,Coffee,Drip coffee,Our Old Time Diner Blend Sm,2.00
4,5,2023-01-01,07:22:41,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.20
...,...,...,...,...,...,...,...,...,...,...,...,...
149111,149452,2023-06-30,20:18:41,2,8,Hell's Kitchen,44,2.50,Tea,Brewed herbal tea,Peppermint Rg,5.00
149112,149453,2023-06-30,20:25:10,2,8,Hell's Kitchen,49,3.00,Tea,Brewed Black tea,English Breakfast Lg,6.00
149113,149454,2023-06-30,20:31:34,1,8,Hell's Kitchen,45,3.00,Tea,Brewed herbal tea,Peppermint Lg,3.00
149114,149455,2023-06-30,20:57:19,1,8,Hell's Kitchen,40,3.75,Coffee,Barista Espresso,Cappuccino,3.75
149115,149456,2023-06-30,20:57:19,2,8,Hell's Kitchen,64,0.80,Flavours,Regular syrup,Hazelnut syrup,1.60

In [28]:
df["transaction_date"].min()

Timestamp('2023-01-01 00:00:00')

In [27]:
df["transaction_date"].max()

Timestamp('2023-06-30 00:00:00')

##month buckets

In [10]:
df["month"]="January"
df["transaction_date"] = pd.to_datetime(df["transaction_date"])
df.loc[df["transaction_date"] > pd.Timestamp("2023-01-31"), "month"] = "February"
df.loc[df["transaction_date"] > pd.Timestamp("2023-02-28"), "month"] = "March"
df.loc[df["transaction_date"] > pd.Timestamp("2023-03-31"), "month"] = "April"
df.loc[df["transaction_date"] > pd.Timestamp("2023-04-30"), "month"] = "May"
df.loc[df["transaction_date"] > pd.Timestamp("2023-05-31"), "month"] = "June"
df

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail,total_amount,month
0,1,2023-01-01,07:06:11,2,5,Lower Manhattan,32,3.00,Coffee,Gourmet brewed coffee,Ethiopia Rg,6.00,January
1,2,2023-01-01,07:08:56,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.20,January
2,3,2023-01-01,07:14:04,2,5,Lower Manhattan,59,4.50,Drinking Chocolate,Hot chocolate,Dark chocolate Lg,9.00,January
3,4,2023-01-01,07:20:24,1,5,Lower Manhattan,22,2.00,Coffee,Drip coffee,Our Old Time Diner Blend Sm,2.00,January
4,5,2023-01-01,07:22:41,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.20,January
...,...,...,...,...,...,...,...,...,...,...,...,...,...
149111,149452,2023-06-30,20:18:41,2,8,Hell's Kitchen,44,2.50,Tea,Brewed herbal tea,Peppermint Rg,5.00,June
149112,149453,2023-06-30,20:25:10,2,8,Hell's Kitchen,49,3.00,Tea,Brewed Black tea,English Breakfast Lg,6.00,June
149113,149454,2023-06-30,20:31:34,1,8,Hell's Kitchen,45,3.00,Tea,Brewed herbal tea,Peppermint Lg,3.00,June
149114,149455,2023-06-30,20:57:19,1,8,Hell's Kitchen,40,3.75,Coffee,Barista Espresso,Cappuccino,3.75,June
149115,149456,2023-06-30,20:57:19,2,8,Hell's Kitchen,64,0.80,Flavours,Regular syrup,Hazelnut syrup,1.60,June

In [29]:
df["transaction_time"].min()

datetime.time(6, 0)

In [30]:
df["transaction_time"].max()

datetime.time(20, 59, 32)

##converting transaction_time buckets

In [17]:
import datetime

df["time_bucket"] = "morning"

# Convert 'transaction_time' to datetime objects. It is currently of object Dtype (strings like 'HH:MM:SS').
df["transaction_time_dt"] = pd.to_datetime(df["transaction_time"], format="%H:%M:%S")

# Extract only the time component for comparison
time_only = df["transaction_time_dt"].dt.time

# Define time boundaries using datetime.time objects for accurate comparison
afternoon_start = datetime.time(12, 0, 0) # 12:00:00
evening_start = datetime.time(17, 0, 0)   # 17:00:00
night_start = datetime.time(19, 0, 0)     # 19:00:00

df.loc[time_only >= afternoon_start, "time_bucket"] = "afternoon"
df.loc[time_only >= evening_start, "time_bucket"] = "evening"
df.loc[time_only >= night_start, "time_bucket"] = "night"
df

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail,total_amount,month,period,time_bucket
0,1,2023-01-01,07:06:11,2,5,Lower Manhattan,32,3.00,Coffee,Gourmet brewed coffee,Ethiopia Rg,6.00,January,morning,morning
1,2,2023-01-01,07:08:56,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.20,January,morning,morning
2,3,2023-01-01,07:14:04,2,5,Lower Manhattan,59,4.50,Drinking Chocolate,Hot chocolate,Dark chocolate Lg,9.00,January,morning,morning
3,4,2023-01-01,07:20:24,1,5,Lower Manhattan,22,2.00,Coffee,Drip coffee,Our Old Time Diner Blend Sm,2.00,January,morning,morning
4,5,2023-01-01,07:22:41,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.20,January,morning,morning
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149111,149452,2023-06-30,20:18:41,2,8,Hell's Kitchen,44,2.50,Tea,Brewed herbal tea,Peppermint Rg,5.00,June,morning,night
149112,149453,2023-06-30,20:25:10,2,8,Hell's Kitchen,49,3.00,Tea,Brewed Black tea,English Breakfast Lg,6.00,June,morning,night
149113,149454,2023-06-30,20:31:34,1,8,Hell's Kitchen,45,3.00,Tea,Brewed herbal tea,Peppermint Lg,3.00,June,morning,night
149114,149455,2023-06-30,20:57:19,1,8,Hell's Kitchen,40,3.75,Coffee,Barista Espresso,Cappuccino,3.75,June,morning,night
149115,149456,2023-06-30,20:57:19,2,8,Hell's Kitchen,64,0.80,Flavours,Regular syrup,Hazelnut syrup,1.60,June,morning,night

##price bucket

In [18]:
df["price_bucket"]="low"
df.loc[df["unit_price"]>15,"price_bucket"]="average"
df.loc[df["unit_price"]>30,"price_bucket"]="high"
df

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail,total_amount,month,period,time_bucket,price_bucket
0,1,2023-01-01,07:06:11,2,5,Lower Manhattan,32,3.00,Coffee,Gourmet brewed coffee,Ethiopia Rg,6.00,January,morning,morning,low
1,2,2023-01-01,07:08:56,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.20,January,morning,morning,low
2,3,2023-01-01,07:14:04,2,5,Lower Manhattan,59,4.50,Drinking Chocolate,Hot chocolate,Dark chocolate Lg,9.00,January,morning,morning,low
3,4,2023-01-01,07:20:24,1,5,Lower Manhattan,22,2.00,Coffee,Drip coffee,Our Old Time Diner Blend Sm,2.00,January,morning,morning,low
4,5,2023-01-01,07:22:41,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.20,January,morning,morning,low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149111,149452,2023-06-30,20:18:41,2,8,Hell's Kitchen,44,2.50,Tea,Brewed herbal tea,Peppermint Rg,5.00,June,morning,night,low
149112,149453,2023-06-30,20:25:10,2,8,Hell's Kitchen,49,3.00,Tea,Brewed Black tea,English Breakfast Lg,6.00,June,morning,night,low
149113,149454,2023-06-30,20:31:34,1,8,Hell's Kitchen,45,3.00,Tea,Brewed herbal tea,Peppermint Lg,3.00,June,morning,night,low
149114,149455,2023-06-30,20:57:19,1,8,Hell's Kitchen,40,3.75,Coffee,Barista Espresso,Cappuccino,3.75,June,morning,night,low
149115,149456,2023-06-30,20:57:19,2,8,Hell's Kitchen,64,0.80,Flavours,Regular syrup,Hazelnut syrup,1.60,June,morning,night,low

##quantity_bucket

In [20]:
df["quantity_bucket"]="retail"
df.loc[df["transaction_qty"]>3,"quantity_bucket"]="medium"
df.loc[df["transaction_qty"]>5,"quantity_bucket"]="wholesale"
df

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail,total_amount,month,period,time_bucket,price_bucket,quantity_bucket
0,1,2023-01-01,07:06:11,2,5,Lower Manhattan,32,3.00,Coffee,Gourmet brewed coffee,Ethiopia Rg,6.00,January,morning,morning,low,retail
1,2,2023-01-01,07:08:56,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.20,January,morning,morning,low,retail
2,3,2023-01-01,07:14:04,2,5,Lower Manhattan,59,4.50,Drinking Chocolate,Hot chocolate,Dark chocolate Lg,9.00,January,morning,morning,low,retail
3,4,2023-01-01,07:20:24,1,5,Lower Manhattan,22,2.00,Coffee,Drip coffee,Our Old Time Diner Blend Sm,2.00,January,morning,morning,low,retail
4,5,2023-01-01,07:22:41,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.20,January,morning,morning,low,retail
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149111,149452,2023-06-30,20:18:41,2,8,Hell's Kitchen,44,2.50,Tea,Brewed herbal tea,Peppermint Rg,5.00,June,morning,night,low,retail
149112,149453,2023-06-30,20:25:10,2,8,Hell's Kitchen,49,3.00,Tea,Brewed Black tea,English Breakfast Lg,6.00,June,morning,night,low,retail
149113,149454,2023-06-30,20:31:34,1,8,Hell's Kitchen,45,3.00,Tea,Brewed herbal tea,Peppermint Lg,3.00,June,morning,night,low,retail
149114,149455,2023-06-30,20:57:19,1,8,Hell's Kitchen,40,3.75,Coffee,Barista Espresso,Cappuccino,3.75,June,morning,night,low,retail
149115,149456,2023-06-30,20:57:19,2,8,Hell's Kitchen,64,0.80,Flavours,Regular syrup,Hazelnut syrup,1.60,June,morning,night,low,retail

Groupby: Revenue by store _location

In [21]:
df.groupby(["store_location"],as_index=False).agg(store_revenue=("total_amount","sum"))

    store_location  store_revenue
0          Astoria      232243.91
1   Hell's Kitchen      236511.17
2  Lower Manhattan      230057.25

##revenue by product_id

In [22]:
df.groupby(["product_id"],as_index=False).agg(store_revenue=("total_amount","sum"))

    product_id  store_revenue
0            1        3852.00
1            2        3294.00
2            3        2492.75
3            4        3067.50
4            5        2220.00
..         ...            ...
75          81        6163.00
76          82        2935.00
77          83        4509.00
78          84        2126.40
79          87        8902.20

[80 rows x 2 columns]

##Revenue by product category

In [23]:
df.groupby(["product_category"],as_index=False).agg(store_revenue=("total_amount","sum"))

     product_category  store_revenue
0              Bakery       82315.64
1             Branded       13607.00
2              Coffee      269952.45
3        Coffee beans       40085.25
4  Drinking Chocolate       72416.00
5            Flavours        8408.80
6           Loose Tea       11213.60
7  Packaged Chocolate        4407.64
8                 Tea      196405.95

##revenue by product_type

In [24]:
df.groupby(["product_category"],as_index=False).agg(store_revenue=("total_amount","sum"))

     product_category  store_revenue
0              Bakery       82315.64
1             Branded       13607.00
2              Coffee      269952.45
3        Coffee beans       40085.25
4  Drinking Chocolate       72416.00
5            Flavours        8408.80
6           Loose Tea       11213.60
7  Packaged Chocolate        4407.64
8                 Tea      196405.95

##Merging store_id with Store_location

In [33]:
pf=df['store_id'].unique()
pf

array([5, 8, 3])

In [34]:
pf=df['store_location'].unique()
pf

array(['Lower Manhattan', "Hell's Kitchen", 'Astoria'], dtype=object)

I 1st need to convert the store_id column into text (string) before combining it with store_location. I've updated the code to convert store_id to a string using .astype(str) before concatenation.

In [39]:
df['store_area'] = df['store_id'].astype(str) + '.' + df['store_location']
df

,transaction_id,transaction_date,transaction_time,transaction_qty,store_id,store_location,product_id,unit_price,product_category,product_type,product_detail,total_amount,month,period,time_bucket,price_bucket,quantity_bucket,store_area
0,1,2023-01-01,07:06:11,2,5,Lower Manhattan,32,3.00,Coffee,Gourmet brewed coffee,Ethiopia Rg,6.00,January,morning,morning,low,retail,5.Lower Manhattan
1,2,2023-01-01,07:08:56,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.20,January,morning,morning,low,retail,5.Lower Manhattan
2,3,2023-01-01,07:14:04,2,5,Lower Manhattan,59,4.50,Drinking Chocolate,Hot chocolate,Dark chocolate Lg,9.00,January,morning,morning,low,retail,5.Lower Manhattan
3,4,2023-01-01,07:20:24,1,5,Lower Manhattan,22,2.00,Coffee,Drip coffee,Our Old Time Diner Blend Sm,2.00,January,morning,morning,low,retail,5.Lower Manhattan
4,5,2023-01-01,07:22:41,2,5,Lower Manhattan,57,3.10,Tea,Brewed Chai tea,Spicy Eye Opener Chai Lg,6.20,January,morning,morning,low,retail,5.Lower Manhattan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149111,149452,2023-06-30,20:18:41,2,8,Hell's Kitchen,44,2.50,Tea,Brewed herbal tea,Peppermint Rg,5.00,June,morning,night,low,retail,8.Hell's Kitchen
149112,149453,2023-06-30,20:25:10,2,8,Hell's Kitchen,49,3.00,Tea,Brewed Black tea,English Breakfast Lg,6.00,June,morning,night,low,retail,8.Hell's Kitchen
149113,149454,2023-06-30,20:31:34,1,8,Hell's Kitchen,45,3.00,Tea,Brewed herbal tea,Peppermint Lg,3.00,June,morning,night,low,retail,8.Hell's Kitchen
149114,149455,2023-06-30,20:57:19,1,8,Hell's Kitchen,40,3.75,Coffee,Barista Espresso,Cappuccino,3.75,June,morning,night,low,retail,8.Hell's Kitchen
149115,149456,2023-06-30,20:57:19,2,8,Hell's Kitchen,64,0.80,Flavours,Regular syrup,Hazelnut syrup,1.60,June,morning,night,low,retail,8.Hell's Kitchen